Update message for entity with missing links
google/digitalbuildings pull request #1012
Opened 2023-04-19 17:44 UTC by trav3711

Updating missing links message to conform to instance validator messaging schema.

2023-04-19 17:46 UTC, tasodorff approved these changes
LGTM

2023-04-19 18:17 UTC, charbull requested changes

2023-04-19 18:17 UTC, charbull commented on tools/validators/instance_validator/validate/entity_instance.py
> +          print(f'[ERROR]\t Required field {field_name} is missing from links for {entity.guid} ({entity.code})')
```
print(f'[ERROR]\t Required field {field_name} is missing from links for entity with Guid: {entity.guid} and Code: ({entity.code})')
```
nit add the guid and code?

2023-04-20 02:44 UTC, trav3711 commented on tools/validators/instance_validator/validate/entity_instance.py
> +          print(f'[ERROR]\t Required field {field_name} is missing from links for {entity.guid} ({entity.code})')
Done.

2023-04-20 17:56 UTC, charbull approved these changes

2023-04-20 18:08 UTC, merged