Addition of a new FCU type for Warm air curtain.
google/digitalbuildings pull request #1016
Opened 2023-04-25 09:07 UTC by ghairapetian

2023-06-14 20:51 UTC, shambergoldstein requested changes

2023-06-14 20:51 UTC, shambergoldstein commented on ontology/yaml/resources/HVAC/entity_types/FCU.yaml
> +FCU_DFSMC_HWRC:
`DFSMC` should have `DFSS` with it.

2023-06-15 15:47 UTC, shambergoldstein approved these changes

2023-06-16 20:53 UTC, cstirdivant requested changes

2023-06-16 20:53 UTC, cstirdivant commented on ontology/yaml/resources/states/states.yaml
> +VERY_LOW : Very low speed or output setting.
This is not an acceptable state because "VERY" is subjective. Can you please elaborate on the total number of discrete speed states this FCU has.

2023-09-18 08:14 UTC, ghairapetian commented
Hello,
The speed states are OFF, 1, 2, 3, 4, 5
1 is the lowest, 5 is the maximum speed.
There are 6 total speed states including OFF.

2023-10-02 22:41 UTC, cstirdivant commented
> Hello, The speed states are OFF, 1, 2, 3, 4, 5 1 is the lowest, 5 is the maximum speed. There are 6 total speed states including OFF.

@ghairapetian 
Thank you for the info. Do you know if the speeds are linearly distributed? For example, could we safely assume that 1 = 20% speed, 2 = 20% speed, 3 = 40% speed, 4 = 60% speed, and 5 = 100% speed?

2023-10-30 09:46 UTC, ghairapetian commented
> > Hello, The speed states are OFF, 1, 2, 3, 4, 5 1 is the lowest, 5 is the maximum speed. There are 6 total speed states including OFF.
> 
> @ghairapetian Thank you for the info. Do you know if the speeds are linearly distributed? For example, could we safely assume that 1 = 20% speed, 2 = 40% speed, 3 = 60% speed, 4 = 80% speed, and 5 = 100% speed?

Hello,
No we can't. It could be distributed from 0 to 50%. Depends of the integration on site.

2023-12-01 19:20 UTC, cstirdivant commented
@ghairapetian thank you for the clarification - for your particular integration, we will need to know exactly what the speed distributions are for each piece of equipment with this type of fan speed control. What you will end up doing is adding the discrete numeric speed states to `discharge_fan_speed_mode` as follows (using the appropriate numbers, I am using 20, 40, 60, 80 as an example):
```
- discharge_fan_speed_mode:
  - AUTO 
  - LOW
  - MEDIUM
  - HIGH
  - OFF
  - VFD
  - 20_PERCENT ## in your example this would map to speed state 1
  - 40_PERCENT ## speed state 2
  - 60_PERCENT ## speed state 3
  - 80_PERCENT ## speed state 4, etc, etc
  ```

2023-12-04 11:14 UTC, ghairapetian commented
Correction done. I checked out and it seems to by linear up to 100% in my case.

However, seems to not pass the ontology validation script.

2023-12-05 09:07 UTC, ghairapetian commented
Done.

2023-12-05 17:24 UTC, cstirdivant approved these changes

2023-12-05 17:29 UTC, merged