New tank type
google/digitalbuildings pull request #1025
Opened 2023-05-10 11:42 UTC by kevin-hereworks

2023-06-12 19:30 UTC, shambergoldstein commented on ontology/yaml/resources/HVAC/entity_types/ABSTRACT.yaml
> +TLM2X:
See above comment.

2023-07-03 13:19 UTC, kevin-hereworks commented on ontology/yaml/resources/fields/telemetry_fields.yaml
> +
this is to set the temperature at which an alarm will be triggered, maybe not very useful in hindsight

2023-07-05 15:13 UTC, cstirdivant requested changes

2023-07-05 15:13 UTC, cstirdivant commented on ontology/yaml/resources/fields/telemetry_fields.yaml
> +
If you are including the alarm point itself there is no need to include the threshold at which the alarm is triggered; so you can remove this point and the model will still be complete.

2024-11-14 12:20 UTC, closed without merging