New boiler and fan entities
google/digitalbuildings pull request #1033
Opened 2023-05-15 15:52 UTC by annieDehghani

Added a new boiler type. 
Added a new fan type.
Moved fields on to opt_uses  for generator, ATS and circ pump.

2023-05-23 23:02 UTC, tasodorff requested changes
We cannot move fields from USES to OPT_USES. New types are required, but its probably more appropriate in your deployment to use MISSING fields in the BC translation, if they are truly missing.

2023-05-23 23:02 UTC, tasodorff commented on ontology/yaml/resources/HVAC/entity_types/FAN.yaml
> +FAN_VSC:
This should not be needed, as `FAN_SS_VSC` exists. Please use that.

2023-05-23 23:02 UTC, tasodorff requested changes
We cannot move fields from USES to OPT_USES. New types are required, but its probably more appropriate in your deployment to use MISSING fields in the BC translation, if they are truly missing.

2023-05-25 20:55 UTC, annieDehghani commented
@tasodorff thank you for that feedback. I was not aware of the option to use MISSING in the translation. Thank you for pointing me to that.

2023-05-30 22:25 UTC, closed without merging