Addition of a new fan for parking.
google/digitalbuildings pull request #1207
Opened 2023-12-04 15:05 UTC by ghairapetian

2023-12-04 19:23 UTC, cstirdivant requested changes

2023-12-04 19:23 UTC, cstirdivant commented on ontology/yaml/resources/HVAC/entity_types/ABSTRACT.yaml
> +COC2DSP:
Please revise name to `CO2C2XDSP`

2023-12-04 19:23 UTC, cstirdivant commented on ontology/yaml/resources/HVAC/entity_types/ABSTRACT.yaml
> +NO2C2DSP:
Please revise name to `NO2C2XDSP`

2023-12-05 09:32 UTC, ghairapetian commented on ontology/yaml/resources/HVAC/entity_types/ABSTRACT.yaml
> +COC2DSP:
Done.

2023-12-05 09:32 UTC, ghairapetian commented on ontology/yaml/resources/HVAC/entity_types/ABSTRACT.yaml
> +NO2C2DSP:
Done.

2023-12-05 17:18 UTC, merged