Added new HWS, CT and HX canonical types, new riser general and abstracts
google/digitalbuildings pull request #1282
Opened 2024-02-21 23:51 UTC by evgeniya-engel

2024-02-22 00:09 UTC, evgeniya-engel commented
@cstirdivant hey Claire, this one is ready for review. Couldn't add you as a reviewer.

2024-02-22 15:17 UTC, cstirdivant requested changes

2024-02-22 15:17 UTC, cstirdivant commented on ontology/yaml/resources/HVAC/entity_types/ABSTRACT.yaml
> +  - primary_supply_water_heating_thermal_power_sensor
remove `supply`

2024-02-22 15:17 UTC, cstirdivant commented on ontology/yaml/resources/HVAC/entity_types/ABSTRACT.yaml
> +  opt_uses:
suggest only adding opt uses that are in your instance

2024-02-22 23:29 UTC, cstirdivant commented on ontology/yaml/resources/HVAC/entity_types/HX.yaml
> +  description: "Heat exchanger with condending return isolation valve, chilled return diverting valve, and chilled and condensing temperature differential monitoring."
typo in this description

2024-02-26 19:33 UTC, cstirdivant approved these changes

2024-02-26 19:34 UTC, merged