UPSAddBattTime2
google/digitalbuildings pull request #1293
Opened 2024-03-13 13:24 UTC by briancjohns

2024-03-19 17:32 UTC, cstirdivant submitted a review, later dismissed

2024-03-19 17:33 UTC, cstirdivant commented
@briancjohns  please address validator error

2024-03-19 17:45 UTC, cstirdivant requested changes

2024-03-19 17:45 UTC, cstirdivant commented on ontology/yaml/resources/fields/telemetry_fields.yaml
> +- remaining_battery_discharge_time_sensor:
See validator message, this field name violates the ordering rules

2024-03-19 19:05 UTC, briancjohns reviewed
resolved the telemetry fields validation error

2024-03-26 20:51 UTC, cstirdivant approved these changes

2024-03-26 20:52 UTC, cstirdivant commented
Scheduled merge for 3/28

2024-04-08 16:47 UTC, merged