AHU Canonical Type having Four EC Fans
google/digitalbuildings pull request #1404
Opened 2024-08-27 10:09 UTC by darshanjain12

"AHU with static pressure-based EC fan speed control, return air temperature-based chilled water valve modulation, filter status monitoring, and four EC fan parameter monitoring."

2024-08-29 20:21 UTC, shambergoldstein commented on ontology/yaml/resources/HVAC/entity_types/AHU.yaml
> +AHU_SFSS_SFVSC_CHWRC_SSPC_FDPSM_SF4FM::
Please clarify - is the set of fans referred to by `SF4FM` separate from the supply fan referred to by `SFSS` and `SFVSC`? Can you explain a bit more about its control?

2024-09-23 09:42 UTC, darshanjain12 commented
@shambergoldstein Please review

2024-09-23 14:39 UTC, shambergoldstein commented
@darshanjain12 please respond to my question from my previous review

2024-09-23 15:29 UTC, darshanjain12 commented
> @darshanjain12 please respond to my question from my previous review

I Have repliea

> @darshanjain12 please respond to my question from my previous review

It is not separate from SFSS and SFVSC however one AHU comprises of 4 physically separate EC Fan. These fans are speed controlled from single analog output. Each fan is monitored via software integration with following points

supply_fan_energy_accumulator
supply_fan_power_sensor
supply_fan_voltage_sensor
supply_fan_current_sensor
supply_fan_rotationalvelocity_sensor

2024-10-08 15:51 UTC, shambergoldstein commented
@darshanjain12 do the fans have individual run statuses?

2024-10-08 16:24 UTC, darshanjain12 commented
> @darshanjain12 do the fans have individual run statuses?

No We are not having individual fans runstatus

2024-10-12 18:15 UTC, darshanjain12 commented
@shambergoldstein Request you to review

2024-10-14 20:19 UTC, shambergoldstein requested changes

2024-10-15 07:24 UTC, darshanjain12 commented
@shambergoldstein Done the Required changes as per your comments to keep the model consistent.
Please review

2024-10-16 14:18 UTC, shambergoldstein requested changes

2024-10-16 14:18 UTC, shambergoldstein commented on ontology/yaml/resources/HVAC/entity_types/AHU.yaml
> +AHU_SFSS4X_SFVSC4X_CHWRC_SSPC_FDPSM::
As a final change please add a form of economizing.

2024-10-16 14:20 UTC, shambergoldstein requested changes

2024-10-16 14:20 UTC, shambergoldstein commented on ontology/yaml/resources/HVAC/entity_types/ABSTRACT.yaml
> +  - MONITOR
please keep as monitoring

2024-10-18 21:27 UTC, shambergoldstein commented on ontology/yaml/resources/HVAC/entity_types/AHU.yaml
> +AHU_SFSS4X_SFVSC4X_CHWRC_SSPC_FDPSM::
@darshanjain12 please see this request

2024-10-19 02:29 UTC, darshanjain12 commented
> @darshanjain12 please respond to my question from my previous review

There is no economizer in the system

2024-10-21 15:41 UTC, shambergoldstein commented
@darshanjain12 as we expect typical AHUs to have economizing, please either add a form of economizing and mark the fields as missing in the building config, or make this a non-canonical type.

2024-10-22 13:50 UTC, darshanjain12 commented
> @darshanjain12 as we expect typical AHUs to have economizing, please either add a form of economizing and mark the fields as missing in the building config, or make this a non-canonical type.

@shambergoldstein Done added Economizer

2024-10-22 14:27 UTC, shambergoldstein commented
@darshanjain12 please resolve the ontology validator error, after that it should be good to merge

2024-10-22 14:33 UTC, darshanjain12 commented
> @darshanjain12 please resolve the ontology validator error, after that it should be good to merge

Done Changes

2024-10-22 15:12 UTC, shambergoldstein approved these changes

2024-10-22 15:13 UTC, merged