Addin DAIDC and RAIDC
google/digitalbuildings pull request #1405
Opened 2024-08-27 10:36 UTC by darshanjain12

As dampers are not to be modeled separately if they are part of a larger system, as suggested in closed pull request number 1389.

2024-08-30 17:20 UTC, shambergoldstein requested changes

2024-08-30 17:20 UTC, shambergoldstein commented on ontology/yaml/resources/HVAC/entity_types/FCU.yaml
> +  description: "Typical chilled water FCU with cooling-only zone control, run mode monitoring, and discharge and return damper command and status monitoring.."
please remove the extra period in the description

2024-09-01 05:12 UTC, darshanjain12 commented
@shambergoldstein  Please review

2024-09-04 14:14 UTC, shambergoldstein approved these changes

2024-09-04 14:27 UTC, merged