New water meter types
google/digitalbuildings pull request #1413
Opened 2024-09-19 17:37 UTC by evgeniya-engel

2024-09-19 17:37 UTC, evgeniya-engel commented
@shambergoldstein hey Shamber, it's ready for your review!

2024-09-20 20:46 UTC, shambergoldstein requested changes

2024-09-20 20:46 UTC, shambergoldstein commented on ontology/yaml/resources/subfields/subfields.yaml
> +  waste: "Substance generated after the use in a variety of deliberate applications or processes."
reword to "An undesirable substance gathered in a fluid as it goes through deliberate applications or processes"

2024-09-20 20:46 UTC, shambergoldstein commented on ontology/yaml/resources/subfields/subfields.yaml
> +  recirculation: "A process of moving substance through a system or loop more than once to achieve a desired condition."
nit: change to "moving a substance"

2024-09-21 00:09 UTC, evgeniya-engel commented
@shambergoldstein addressed your comments, thank you!

2024-09-23 14:36 UTC, shambergoldstein approved these changes

2024-09-23 14:53 UTC, merged