Added differential temperatures and abstract types
google/digitalbuildings pull request #1416
Opened 2024-09-23 16:12 UTC by pranay2811

Telemetry fields: 
chilled_water_differential_temperature_sensor, chilled_water_differential_temperature_setpoint;
condensing_water_differential_temperature_sensor, condensing_water_differential_temperature_setpoint;
heating_water_differential_temperature_sensor, heating_water_differential_temperature_setpoint

Abstract Types:
CHWDTC;
CWTDC;
HWDTC

2024-09-23 16:13 UTC, pranay2811 commented
@shambergoldstein This is ready for review

2024-09-24 14:54 UTC, shambergoldstein requested changes
Add guids - see comment on PR #1415. Otherwise lgtm.

2024-09-24 15:55 UTC, pranay2811 commented
@shambergoldstein I have added the guids

2024-09-24 18:37 UTC, shambergoldstein approved these changes

2024-09-24 18:47 UTC, merged