Added HM_STEAM & corresponding telemetry fields
google/digitalbuildings pull request #1417
Opened 2024-09-23 19:01 UTC by pranay2811

New telemtery fields:
steam_massflow_sensor
supply_steam_temperature_sensor
steam_volume_accumulator

New Canoncial Type:
HM_STEAM

2024-09-23 19:02 UTC, pranay2811 commented
@shambergoldstein Ready for your review

2024-09-24 14:56 UTC, shambergoldstein requested changes
Add guid - see comment on PR #1415. Otherwise lgtm

2024-09-24 17:39 UTC, pranay2811 commented
Added guid for HM_STEAM @shambergoldstein

2024-09-24 18:39 UTC, shambergoldstein approved these changes

2024-09-24 18:58 UTC, merged