Added DSPC & discharge_air_static_pressure_setpoint
google/digitalbuildings pull request #1418
Opened 2024-09-23 19:29 UTC by pranay2811

2024-09-23 19:29 UTC, pranay2811 commented
@shambergoldstein Ready for your review

2024-09-24 15:01 UTC, shambergoldstein requested changes
Add guid - see comment on #1415. Otherwise lgtm

2024-09-24 17:41 UTC, pranay2811 commented
Added guid for DSPC @shambergoldstein

2024-09-24 18:41 UTC, shambergoldstein approved these changes

2024-09-24 18:59 UTC, merged