Added Motor Rotational Velocity
google/digitalbuildings pull request #1421
Opened 2024-09-23 21:15 UTC by pranay2811

Added telemetry fields:
- motor_rotationalvelocity_sensor
- motor_rotationalvelocity_setpoint

Added Abstract Type:
- MRVC

2024-09-23 21:16 UTC, pranay2811 commented
@shambergoldstein Ready for your review

2024-09-24 19:01 UTC, pranay2811 commented
@shambergoldstein How do I resolve the conflicts in this branch?

2024-09-24 19:27 UTC, shambergoldstein requested changes

2024-09-24 19:27 UTC, shambergoldstein commented on ontology/yaml/resources/fields/telemetry_fields.yaml
please add spaces after "-"

2024-09-24 19:34 UTC, pranay2811 commented on ontology/yaml/resources/fields/telemetry_fields.yaml
done

2024-09-25 15:14 UTC, shambergoldstein approved these changes

2024-09-25 15:28 UTC, shambergoldstein requested changes

2024-09-25 15:28 UTC, shambergoldstein commented on ontology/yaml/resources/fields/telemetry_fields.yaml
typo on these; "fixed_mind", please fix

2024-09-25 15:33 UTC, pranay2811 commented on ontology/yaml/resources/fields/telemetry_fields.yaml
Fixed it.

2024-09-25 15:55 UTC, shambergoldstein approved these changes

2024-09-25 15:55 UTC, merged