Added CHW/CW bypass valves
google/digitalbuildings pull request #1426
Opened 2024-09-24 18:56 UTC by pranay2811

Added fields:
chilled_water_bypass_valve_command
chilled_water_bypass_valve_status
chilled_water_valve_status
condensing_water_bypass_valve_command
condensing_water_bypass_valve_status

Added Abstracts
CHWBYPVBRC & CWBYPVBRC

2024-09-24 18:56 UTC, pranay2811 commented
@shambergoldstein This is ready for your review

2024-09-25 15:25 UTC, shambergoldstein requested changes

2024-09-25 15:25 UTC, shambergoldstein commented on ontology/yaml/resources/HVAC/entity_types/ABSTRACT.yaml
> +  - condensing_water_bypass_valve_status
please move this to the required uses

2024-09-25 15:25 UTC, shambergoldstein commented on ontology/yaml/resources/HVAC/entity_types/ABSTRACT.yaml
> +  - chilled_water_bypass_valve_status
please move this to required uses

2024-09-25 15:38 UTC, pranay2811 commented on ontology/yaml/resources/HVAC/entity_types/ABSTRACT.yaml
> +  - chilled_water_bypass_valve_status
Done

2024-09-25 15:38 UTC, pranay2811 commented on ontology/yaml/resources/HVAC/entity_types/ABSTRACT.yaml
> +  - condensing_water_bypass_valve_status
Done

2024-09-25 15:44 UTC, shambergoldstein commented on ontology/yaml/resources/HVAC/entity_types/ABSTRACT.yaml
What does the R represent in the abstract type names? I think it makes sense to change these to CHWBYPVBC and CWBYPVBC (...water bypass valve binary control).

2024-09-25 15:50 UTC, pranay2811 commented on ontology/yaml/resources/HVAC/entity_types/ABSTRACT.yaml
I think I saw an abstract type ending in BRC. Looks like the r represents return which is not the case for these abstracts. I will edit them now

2024-09-25 15:51 UTC, pranay2811 commented on ontology/yaml/resources/HVAC/entity_types/ABSTRACT.yaml
Done

2024-09-25 15:56 UTC, shambergoldstein approved these changes

2024-09-25 16:15 UTC, merged