Energy Meter Improvements
google/digitalbuildings pull request #143
Opened 2020-11-05 23:32 UTC by tasodorff

Extended energy meters and refactored some underlying abstract types.

Only one existing energy meter was impacted, with changes being to inherit fields from abstract concepts instead of through direct definition of fields on that type (EM_ION).

2020-11-06 01:03 UTC, berkoben requested changes

2020-11-09 02:04 UTC, tasodorff commented on ontology/yaml/resources/METERS/entity_types/POWER_METER.yaml
> +EM_ION: # TODO: should rename to standard convention.
fixed in new commit

2020-11-09 02:27 UTC, tasodorff commented on ontology/yaml/resources/METERS/entity_types/POWER_METER.yaml
> +EM_ONEOFF_1:
i will remove them, they definitely are not valid canonical configurations.

2020-11-12 19:54 UTC, berkoben requested changes

2020-11-16 21:27 UTC, tasodorff commented on ontology/yaml/resources/METERS/entity_types/ABSTRACT.yaml
> +  - average_line_voltage_sensor # Line to line
i think that is fine. i will update.

2020-11-16 21:31 UTC, berkoben approved these changes

2020-11-16 21:31 UTC, berkoben commented on ontology/yaml/resources/METERS/entity_types/ABSTRACT.yaml
> +  - average_line_voltage_sensor # Line to line
yes, and I see you've updated it.

2020-11-16 21:34 UTC, tasodorff commented on ontology/yaml/resources/METERS/entity_types/ABSTRACT.yaml
> +  is_abstract: true
There is probably a difference between the way that you and I think about the function of 'canonical': I don't consider something canonical unless it represents a concrete device (such as a VAV_SD, which we will find in the wild); there may be wonky devices where we may argue over if its truly canonical, but they are all inevitably concrete. An abstract type, by comparison, does not have any concrete manifestation in and of itself -- it is always an abstraction of function (or something else, such as a convenient grouping of fields) and must therefore always be implemented by a concrete canonical type, even if it is a 1:1 mapping.

2020-11-17 19:18 UTC, merged