Added Glycol Temperature & Pressure fields
google/digitalbuildings pull request #1451
Opened 2024-10-24 20:55 UTC by pranay2811

2024-10-24 20:56 UTC, pranay2811 commented
@shambergoldstein Ready for review

2024-10-24 22:20 UTC, shambergoldstein requested changes

2024-10-24 22:20 UTC, shambergoldstein commented on ontology/yaml/resources/HVAC/entity_types/ABSTRACT.yaml
> +  is_abstract: ture
typo on "true"

2024-10-25 18:05 UTC, pranay2811 commented on ontology/yaml/resources/HVAC/entity_types/ABSTRACT.yaml
> +  is_abstract: ture
@shambergoldstein Done

2024-10-25 19:43 UTC, shambergoldstein approved these changes

2024-10-25 19:44 UTC, merged