Hydronic system additions
google/digitalbuildings pull request #1465
Opened 2024-11-12 21:20 UTC by evgeniya-engel

2024-11-12 21:29 UTC, evgeniya-engel commented
@shambergoldstein @ccquigley ready for your review! Thank you!

2024-11-13 01:44 UTC, evgeniya-engel commented
@shambergoldstein @ccquigley this should be final

2024-11-13 16:29 UTC, shambergoldstein requested changes

2024-11-13 16:29 UTC, shambergoldstein commented on ontology/yaml/resources/HVAC/entity_types/ABSTRACT.yaml
> +BYPVFRC:
can you just use the combination of `BYPVPM` and `WFRC`?

2024-11-13 17:15 UTC, ccquigley approved these changes

2024-11-13 17:15 UTC, merged