hydronic: new fields, abstracts and equipment types
google/digitalbuildings pull request #1469
Opened 2024-11-25 22:54 UTC by evgeniya-engel

2024-11-26 18:07 UTC, evgeniya-engel commented
@shambergoldstein @cquigley2 ready for your review. Thank you!

2024-11-26 23:06 UTC, shambergoldstein approved these changes

2024-11-26 23:08 UTC, shambergoldstein requested changes

2024-11-26 23:08 UTC, shambergoldstein commented on ontology/yaml/resources/fields/telemetry_fields.yaml
> +    - OFF
nit: states are tabbed over extra, please fix

2024-11-26 23:23 UTC, evgeniya-engel commented on ontology/yaml/resources/fields/telemetry_fields.yaml
> +    - OFF
my bad, fixed

2024-11-27 15:00 UTC, shambergoldstein approved these changes

2024-11-27 15:10 UTC, merged