Move filter and smoke alarm from DOAS to MAU type
google/digitalbuildings pull request #1478
Opened 2024-12-07 17:47 UTC by terryterpt

2024-12-07 17:49 UTC, terryterpt commented
Hi @shambergoldstein , I have forgotten to move the filter and smoke alarm from DOAS to MAU general type on the previous pull request.

I have done it now, please assist to approve this

2024-12-09 15:30 UTC, shambergoldstein requested changes

2024-12-09 15:30 UTC, shambergoldstein commented on ontology/yaml/resources/HVAC/entity_types/GENERALTYPES.yaml
please keep the alarms on the DOAS as well (in case any devices have been onboarded using them since the last merge)

2024-12-17 08:50 UTC, terryterpt commented on ontology/yaml/resources/HVAC/entity_types/GENERALTYPES.yaml
I have added back the alarms to DOAS

2024-12-17 08:50 UTC, terryterpt commented
I also added a new type for LS

2024-12-17 15:52 UTC, shambergoldstein requested changes

2024-12-17 15:52 UTC, shambergoldstein commented on ontology/yaml/resources/LIGHTING/entity_types/ABSTRACT.yaml
can the existing `DM` abstract be used instead?

2024-12-17 15:52 UTC, shambergoldstein commented on ontology/yaml/resources/LIGHTING/entity_types/LS.yaml
see comment on abstract

2024-12-18 03:57 UTC, terryterpt commented on ontology/yaml/resources/LIGHTING/entity_types/ABSTRACT.yaml
I dont think so. We are monitoring the illuminance of the light measured in percentage and not the brightness

2024-12-18 15:52 UTC, shambergoldstein approved these changes

2024-12-18 15:52 UTC, merged