Add Trench Heating file
google/digitalbuildings pull request #248
Opened 2021-04-09 10:53 UTC by oli-barker

2021-04-09 10:55 UTC, oli-barker commented
Setting up new building please ignore

2021-04-09 22:27 UTC, charbull commented
Hi @oli-barker can you please sign the cla

Thank you

2021-04-09 22:28 UTC, charbull commented on ontology/yaml/resources/fields/telemetry_fields.yaml
> +# Added for UK-LON-X1
can you please remove this tag (UK-LON-X1)

2021-04-12 13:14 UTC, oli-barker commented
> @googlebot I signed it

2021-04-12 13:15 UTC, oli-barker commented
> @googlebot I signed it!

2021-04-20 15:43 UTC, tasodorff requested changes
Main comment is to change trench heater abbreviation to match BOS standard. Several minor fixes (remove all IDs, add a few requested abstract types, type name should match concatenated 'implements' types by convention, etc.).

2021-04-20 15:43 UTC, tasodorff commented on ontology/yaml/resources/HVAC/entity_types/GENERALTYPES.yaml
> +TRU:
Doesn't match BOS v2.3 standard. Fix this.

2021-04-20 15:43 UTC, tasodorff commented on ontology/yaml/resources/HVAC/entity_types/GENERALTYPES.yaml
> +  id: "oli0001"
Omit all IDs, the system will append these if needed.

2021-04-20 15:43 UTC, tasodorff commented on ontology/yaml/resources/HVAC/entity_types/GENERALTYPES.yaml
> +  description: "Tag for trench heating units. Trench Heating units are in floor airconditioning units.
Clarify "particular to under-floor air distribution systems" or something similar.

2021-04-20 15:43 UTC, tasodorff commented on ontology/yaml/resources/HVAC/entity_types/TRU.yaml
> +TRH_DFSS_DFVSC_DSP_CHWZC:
This name doesn't match the types implemented below. These should match by convention.

2021-04-20 15:43 UTC, tasodorff commented on ontology/yaml/resources/HVAC/entity_types/TRU.yaml
> +  - TRU
fix

2021-04-20 15:43 UTC, tasodorff commented on ontology/yaml/resources/HVAC/entity_types/TRU.yaml
> +  - DFVSC
Please also implement DFSS

2021-04-20 15:43 UTC, tasodorff commented on ontology/yaml/resources/HVAC/entity_types/TRU.yaml
> +  - DFVSC
Same note as above; please implement DFSS also

2021-04-20 15:43 UTC, tasodorff commented on ontology/yaml/resources/HVAC/entity_types/TRU.yaml
> +TRH_DFSS_DFVSC_DSP_HWZC_CHWZC:
Same note as above; match implemented types.

2021-04-20 15:43 UTC, tasodorff commented on ontology/yaml/resources/METERS/entity_types/HM.yaml
> +  id: "oli0004"
reminder to remove all fake IDs

2021-04-21 14:30 UTC, tasodorff commented
I still don't see the type names updated in your latest PR.

2021-04-21 14:40 UTC, oli-barker commented
> I still don't see the type names updated in your latest PR.

I updated the TRU entry in general types to TRH in line with BOS 2.3. Also changed the TRU.yaml file to TRH.yaml and defined 2 types of trench heater. One with just heating and one with both. I haven't defined TRHC as its effectively a subtype of the main item. This seemed the same in line with FCU where it can be any configuration of heating and cooling etc but is still an FCU.

2021-05-20 15:49 UTC, tasodorff requested changes
Clarifications needed on some definitions, and alternate names required.

2021-05-20 15:49 UTC, tasodorff commented on ontology/yaml/resources/HVAC/entity_types/AHU.yaml
> +AHU_UK_LON_X1_1:
A few notes:
1. Why dont we have any information for the supply/exhaust fans (command/status/speeds), orr any outside air information?
2. Do not use the name of the site in the type name.

2021-05-20 15:49 UTC, tasodorff commented on ontology/yaml/resources/HVAC/entity_types/AHU.yaml
> +AHU_UK_LON_X1_2:
Same note as above -- remove Google specific name.

2021-05-20 15:49 UTC, tasodorff commented on ontology/yaml/resources/fields/telemetry_fields.yaml
> +- heating_wheel_percentage_sensor
heating wheel what percentage sensor? 

percent of air flowing through it? speed at which its rotating? percent capacity? needs more specificity.

2021-05-20 15:49 UTC, tasodorff commented on ontology/yaml/resources/fields/telemetry_fields.yaml
> +- cooling_coil_percentage_command
is this the valve?

2021-05-20 15:49 UTC, tasodorff commented on ontology/yaml/resources/fields/telemetry_fields.yaml
> +- heating_coil_percentage_command
why are you using this and not heating_water_valve_percentage command? is it not hydronic? if not, what is it?

2021-05-20 15:49 UTC, tasodorff commented on ontology/yaml/resources/fields/telemetry_fields.yaml
> +- frost_coil_status:
again, what is this a status of? flow through coil?

2021-05-20 15:49 UTC, tasodorff commented on ontology/yaml/resources/fields/telemetry_fields.yaml
> +- min_supply_air_temperature_setpoint
same as above; use `low_limit` if not an aggregation.

2021-10-07 16:38 UTC, tasodorff commented
@oli-barker what is the status of these? please make changes or the PR will be closed without committing the changes.

2022-01-06 00:09 UTC, tasodorff commented
@oli-barker status?

2022-04-01 20:59 UTC, tasodorff commented
Closed due to inactivity. Can reopen if necessary.

2022-04-01 20:59 UTC, closed without merging