Malaysia building
google/digitalbuildings pull request #262
Opened 2021-05-12 05:15 UTC by conroy-chee

Initialize Malaysia dbo

*Changes on HVAC ABSTRACT.yaml, AHU.yaml, FCU.yaml, GENERALTYPES.yaml, SENSOR.yaml and VAV.yaml
*Changes on SAFETY ABSTRACT.yaml and LDS.yaml
*Added HVAC VRV.yaml and METERS FM.yaml

2021-05-13 03:11 UTC, tasodorff requested changes

2021-05-13 03:11 UTC, tasodorff commented on ontology/yaml/resources/HVAC/entity_types/GENERALTYPES.yaml
> +  description: "A single split unit."
If this is a variable refrigerant flow system (VRF) please describe it as such.

2021-05-13 03:11 UTC, tasodorff commented on ontology/yaml/resources/HVAC/entity_types/FCU.yaml
> +  is_canonical: true
If this is a strange one-off device, mark it as non-canonical.

2021-07-01 17:01 UTC, charbull commented
@conroy-chee please fix the following errors: 

Findings in SAFETY/entity_types/LDS.yaml
ERROR : Duplicate type IDs are not allowed. Entity type name "LDS_GASDET" within namespace "SAFETY" with ID "17602426483400245248" was already defined in 
	<SAFETY/entity_types/LDS.yaml> (Line 0).

ERROR : Duplicate type IDs are not allowed. Entity type name "LDS_BC2X_WLA_LPA" within namespace "SAFETY" with ID "17602426483400245248" was already defined in 
	<SAFETY/entity_types/LDS.yaml> (Line 0).

Findings in HVAC/entity_types/VRV.yaml
ERROR : Duplicate type IDs are not allowed. Entity type name "VRV_ZTC_VSC" within namespace "HVAC" with ID "13434279712669433856" was already defined in 
	<HVAC/entity_types/VRV.yaml> (Line 0).

ERROR : Duplicate type IDs are not allowed. Entity type name "VRV_NO_CONTROL" within namespace "HVAC" with ID "13434279712669433856" was already defined in 
	<HVAC/entity_types/VRV.yaml> (Line 0).

Link errors: https://github.com/google/digitalbuildings/pull/262/checks?check_run_id=2936487827

Thank you

2021-07-28 16:30 UTC, tasodorff commented
@conroychee is this still in progress.

2021-08-03 04:48 UTC, closed without merging