CH ZRH EURD
google/digitalbuildings pull request #305
Opened 2021-08-11 13:57 UTC by bsaxpi

PR for additional fields, abstracts, entity types etc. for the CH ZRH EURD building

2021-08-16 19:26 UTC, tasodorff requested changes
A few minor changes requested.

2021-08-16 19:26 UTC, tasodorff commented on ontology/yaml/resources/HVAC/entity_types/HWS.yaml
> +HWS_NON_CANONICAL_TYPE_1:
We dont need to call these out as incomplete here, you would translate them incompletely. This thing would simply be HWS_SWTC and would be canonical; the specific entity in building config would implement HWS_SWTC and have missing fields if they weren't there.

2021-08-16 19:26 UTC, tasodorff commented on ontology/yaml/resources/states/states.yaml
> +FADING: "An operation mode of a lighting dimmer"
Expand definition to distinguish from ramping. Fading goes from high illuminance to low?

2021-08-16 19:26 UTC, tasodorff commented on ontology/yaml/resources/states/states.yaml
> +RAMPING: "An operation mode of a lighting dimmer"
Expand to distinguish from fading; low to high illuminance??

2021-08-19 09:04 UTC, bsaxpi commented
> A few minor changes requested.

Changes done, conflicts resolved

2021-08-20 22:46 UTC, tasodorff approved these changes

2021-08-25 16:48 UTC, merged