Fix duplicate no_units validation error.
google/digitalbuildings pull request #341
Opened 2021-09-27 15:51 UTC by dplute

This patch allows "no_units" to be specified for more than one measurement by giving each one a unique name in the namespace's units map.

2021-09-27 16:28 UTC, dplute commented
@googlebot I signed it!

2021-09-27 19:49 UTC, charbull commented
@dplute are we proposing to support multiple `no_units_$measurement` instead of `no_units` for any possible measurement?

2021-09-27 20:22 UTC, dplute commented
This is meant to support the use of "no_units" for any number of measurements. (e.g. powerfactor, currentratio, voltageratio from #298)

The validator currently cannot do this because it thinks that we are trying to define a unit named "no_units" multiple times in the namespace.  This would recognize "no_units" as a special name and adjust it internally to avoid duplicate keys, which would allow "no_units" to be specified under multiple measurements without causing a duplicate definition error.

2021-09-28 18:32 UTC, charbull commented on tools/validators/ontology_validator/yamlformat/tests/presubmit_validate_types_lib_test.py
> +      'powerfactor': [{'no_units': 'STANDARD'}],
just to make this test more complete can you please use two units one standard and non-standard for powerfactor: no_units, another_one and update the test accordingly

2021-09-28 18:33 UTC, charbull commented on tools/validators/ontology_validator/yamlformat/tests/unit_lib_test.py
> +      'powerfactor': [{'no_units': 'STANDARD'}],
same here test the case where a measurement has two units: no_units, another_one

2021-09-28 18:33 UTC, charbull requested changes
thank you, minor changes

2021-09-28 19:02 UTC, dplute commented
@charbull I have updated the tests.

2021-09-28 19:25 UTC, charbull commented on tools/validators/ontology_validator/yamlformat/tests/presubmit_validate_types_lib_test.py
> -    self.assertSameElements(['no_units'], units)
can you please leave an empty line here, and remove the empty line above, 
we do follow this approach: https://automationpanda.com/2020/07/07/arrange-act-assert-a-pattern-for-writing-good-tests/

we use blank lines to separate the parts.
//Arrange
//blank line
//Act
//blank line
//assert

2021-09-28 19:25 UTC, charbull approved these changes
minor tweeks just for the formatting of tests.
Thank you

2021-09-28 19:44 UTC, charbull commented on tools/validators/ontology_validator/yamlformat/tests/presubmit_validate_types_lib_test.py
> +    units = config_universe.GetUnitsForMeasurement('powerfactor_sensor')
line 251 to move up with the previous config_universe block
then leave empty blank line before self.assertSae...

2021-09-28 19:44 UTC, charbull commented on tools/validators/ontology_validator/yamlformat/tests/unit_lib_test.py
> +    self.assertEmpty(folder.GetFindings())
leave empty line before this line please

2021-09-28 19:44 UTC, charbull requested changes
tests formatting minor tweeks.

2021-09-28 20:20 UTC, dplute commented
@charbull Formatting updated

2021-09-28 20:58 UTC, charbull approved these changes
thank you,
can you please update your branch

2021-09-28 21:07 UTC, dplute commented
@charbull Branch updated

2021-09-28 21:24 UTC, merged