Project import generated by Copybara.
google/digitalbuildings pull request #467
Opened 2022-02-01 22:41 UTC by kswang2400

PiperOrigin-RevId: 425717115

2022-02-01 22:44 UTC, charbull requested changes
it is deleting the scoring code.
I think you can update the copybara file to ignore the scorer for now?

2022-02-01 22:44 UTC, charbull commented on .github/workflows/python_tools.yml
> -    #---------- Configuration scoring ----------#
those are deleted

2022-02-02 15:20 UTC, kswang2400 commented on .github/workflows/python_tools.yml
> -    #---------- Configuration scoring ----------#
Done

2022-02-02 16:58 UTC, trav3711 approved these changes
I'm not sure about the scoring code but all of the changes I want are in there.

2022-02-03 20:01 UTC, charbull commented
closing it in attempt to sync

2022-02-03 20:01 UTC, closed without merging