Addition of a new CHWS type (CHWS_RWTC_CHWVM).
google/digitalbuildings pull request #503
Opened 2022-02-28 12:24 UTC by ghairapetian

2022-03-18 19:31 UTC, tasodorff approved these changes
Remove IDs. Everything else looks good.

2022-03-18 19:31 UTC, tasodorff commented on ontology/yaml/resources/HVAC/entity_types/CHWS.yaml
> +  id: "16842546300862857217"
Please remove ID. New entity types do not require IDs (our system sets the IDs automatically).

2022-03-18 19:31 UTC, tasodorff commented on ontology/yaml/resources/HVAC/entity_types/CHWS.yaml
> +  id: "16842546300862857218"
Please remove ID.

2022-03-18 19:32 UTC, tasodorff requested changes
Meant to request changes instead of approve; please remove IDs.

2022-03-22 16:29 UTC, ghairapetian commented
Something messy happened with the rebase. I will close this pull request and reopen a new one. Sorry for that.

2022-03-22 16:29 UTC, closed without merging