Addition of two new types of HWS (HWS_SWTM_WDPC_BYPVPM and HWS_SWTM_WDPC_BYPVPM_HWVM)
google/digitalbuildings pull request #504
Opened 2022-02-28 12:47 UTC by ghairapetian

2022-03-18 19:29 UTC, tasodorff requested changes

2022-03-18 19:29 UTC, tasodorff commented on ontology/yaml/resources/HVAC/entity_types/HWS.yaml
> +  id: "12025993778390106113"
Please remove ID.

2022-03-18 19:29 UTC, tasodorff commented on ontology/yaml/resources/HVAC/entity_types/HWS.yaml
> +  id: "12025993778390106114"
Please remove ID.

2022-03-22 16:25 UTC, ghairapetian commented on ontology/yaml/resources/HVAC/entity_types/HWS.yaml
> +  id: "12025993778390106114"
Done

2022-03-22 16:28 UTC, ghairapetian commented on ontology/yaml/resources/HVAC/entity_types/HWS.yaml
> +  id: "12025993778390106113"
Done

2022-04-12 03:36 UTC, tasodorff approved these changes
All new combinations of existing abstract types. Looks good to me.

2022-04-14 22:55 UTC, merged