MFA BV100 additions
google/digitalbuildings pull request #514
Opened 2022-03-24 00:12 UTC by tom-skoczylas

Additions for primarily heat recovery, radiant panels, fan coils, makeup air, domestic hot water systems, and tanks. Please review MAU and domestic water additions very carefully. @tasodorff @tsodorff @mschulze17

2022-03-28 15:45 UTC, cstirdivant commented on ontology/yaml/resources/subfields/subfields.yaml
> +  carbon: "Carbon in solid form."
Not necessarily solid form.

2022-03-28 15:56 UTC, cstirdivant requested changes

2022-03-28 15:56 UTC, cstirdivant commented on ontology/yaml/resources/fields/telemetry_fields.yaml
> +- heating_supply_water_isolation_valve_status
add states

2022-03-28 15:56 UTC, cstirdivant commented on ontology/yaml/resources/HVAC/entity_types/ABSTRACT.yaml
> +  description: "Exhaust hydronic heat recovery coil on exhaust to be used elsewhere."
revise description

2022-03-28 15:56 UTC, cstirdivant commented on ontology/yaml/resources/HVAC/entity_types/ABSTRACT.yaml
> +  implements:
please put implements field at the end, see other type structures for precedent

2022-03-28 15:56 UTC, cstirdivant commented on ontology/yaml/resources/HVAC/entity_types/ABSTRACT.yaml
> +  implements:
move section to end of type

2022-03-28 15:56 UTC, cstirdivant commented on ontology/yaml/resources/HVAC/entity_types/ABSTRACT.yaml
> +  implements:
move to end of type

2022-03-28 15:56 UTC, cstirdivant commented on ontology/yaml/resources/HVAC/entity_types/ABSTRACT.yaml
> +  - MONITORING
this implements OPERATIONAL

2022-03-28 15:56 UTC, cstirdivant commented on ontology/yaml/resources/HVAC/entity_types/DHWT.yaml
> +DHWT_PHTTC:
typo

2022-03-30 18:33 UTC, cstirdivant approved these changes

2022-04-14 21:46 UTC, charbull commented
@tasodorff @cstirdivant can this PR be merged?

2022-04-14 23:01 UTC, cstirdivant commented
@charbull please wait to merge, Trevor & I are reviewing tomorrow.

2022-04-20 22:52 UTC, tasodorff requested changes
Please make some minor additions to descriptions and remove building references.

2022-04-20 22:52 UTC, tasodorff commented on ontology/yaml/resources/HVAC/entity_types/ABSTRACT.yaml
> +# New abstracts for MFA BV100 HVAC
Remove references to specific sites, if possible.

2022-04-20 22:52 UTC, tasodorff commented on ontology/yaml/resources/HVAC/entity_types/ABSTRACT.yaml
> +  description: "Carbon filter pressure monitoring."
Please add to description, something like: "Carbon filter pressure monitoring, where specific filter type is required."

2022-04-20 22:52 UTC, tasodorff commented on ontology/yaml/resources/HVAC/entity_types/ABSTRACT.yaml
> +  description: "Variable outside air damper monitoring."
add to description: "[...] where there are two separate, equal sets of dampers that operate in conjunction."

2022-04-20 22:52 UTC, tasodorff commented on ontology/yaml/resources/HVAC/entity_types/ABSTRACT.yaml
> +  each incoming system and a single control valve. Valve and mode control to zone temperature
you mention a single control valve, but I dont see it defined on the type.

2022-04-20 22:52 UTC, tasodorff commented on ontology/yaml/resources/HVAC/entity_types/ABSTRACT.yaml
> +  description: "Floor temperature control"
please add a bit more here: "[...] where the temperatures are embedded in the floor (as opposed to open to the air)."

2022-04-20 22:52 UTC, tasodorff commented on ontology/yaml/resources/HVAC/entity_types/ABSTRACT.yaml
> +# New abstracts for MFA BV100 DHW
same, remove bldg ref

2022-04-21 20:11 UTC, cstirdivant approved these changes

2022-04-22 14:31 UTC, tasodorff approved these changes

2022-04-22 14:58 UTC, merged