Update telemetry_fields_VAV.yaml
google/digitalbuildings pull request #573
Opened 2022-04-28 15:36 UTC by RathishKJ

Hello,

Hereby raising the pull request for the VAVs

-zone_air_occupied_cooling_temperature_setpoint
-zone_air_unoccupied_cooling_temperature_setpoint 

regards,
Rathish

2022-05-11 00:04 UTC, tasodorff requested changes

2022-05-11 00:04 UTC, tasodorff commented on ontology/yaml/resources/HVAC/entity_types/ABSTRACT.yaml
> +  - CONTROL
Include the zone_air_temperature_sensor here, and change from CONTROL to OPERATIONAL. You did not include the actuator (e.g. valve or damper) that actually controls the zone to temperature.

2022-05-11 00:04 UTC, tasodorff commented on ontology/yaml/resources/HVAC/entity_types/VAV.yaml
> +  - DSP
This device will have all of these fields:
- zone_air_temperature_sensor
- zone_air_cooling_temperature_setpoint
- zone_air_heating_temperature_setpoint
- zone_air_unoccupied_cooling_temperature_setpoint
- zone_air_occupied_cooling_temperature_setpoint

Where are the heating setpoints? And why are the unoccupied/occupied setpoints needed if the effective setpoints are already on the device under DSP?

2022-06-01 23:52 UTC, tasodorff commented
@RathishKJ please respond to comments and make changes as necessary.

2022-06-13 16:31 UTC, tasodorff requested changes
Require major changes to VAV definitions. We want to reuse existing VAV types as much as possible, even if your translations to them are incomplete (if the devices don't send you all the data). Model the devices based on what they do, not just based on what data they send us.

2022-06-13 16:31 UTC, tasodorff commented on ontology/yaml/resources/HVAC/entity_types/ABSTRACT.yaml
> +ZA:
this is already defined. why are you redefining it?

2022-06-13 16:31 UTC, tasodorff commented on ontology/yaml/resources/HVAC/entity_types/ABSTRACT.yaml
> +  - max_flowrate_setpoint
unless you are aggregating a bunch of setpoints, this is not a `max_flowrate_setpoint` -- its a high-limit flowrate setpoint. please adjust. i am also confused why you would be controlling to high limit; bypass valves are usually for low-limit flows (that is, to keep the flow in the primary loop above a certain minimum value). what is the control strategy here?

2022-06-13 16:31 UTC, tasodorff commented on ontology/yaml/resources/HVAC/entity_types/ABSTRACT.yaml
> +  id: "16039155144679489536"
you do not need to add IDs, that is done automatically by our system.

2022-06-13 16:31 UTC, tasodorff commented on ontology/yaml/resources/HVAC/entity_types/VAV.yaml
> +VAV_PDSCV:
what does it control to? this seems like an incomplete VAV.

2022-06-13 16:31 UTC, tasodorff commented on ontology/yaml/resources/HVAC/entity_types/VAV.yaml
> +VAV_SFM:
what does it control to? this seems like an incomplete VAV.

2022-06-13 16:31 UTC, tasodorff commented on ontology/yaml/resources/HVAC/entity_types/VAV.yaml
> +VAV_MINFC:
what does it control to? this seems like an incomplete VAV.

2022-06-21 22:50 UTC, tasodorff commented
Make the changes already requested, and ensure the validator tests pass.

2022-06-27 18:05 UTC, RathishKJ commented
Closing the pull request since we have found an existing canonical in the Git...

2022-06-27 18:05 UTC, closed without merging