Addition of a standard type and a non-standard type for DOAS
google/digitalbuildings pull request #585
Opened 2022-05-05 07:26 UTC by ghairapetian

2022-05-10 23:47 UTC, tasodorff requested changes
Minor changes requested.

2022-05-10 23:47 UTC, tasodorff commented on ontology/yaml/resources/HVAC/entity_types/DOAS.yaml
> +DOAS_FR_PAR_50A_1:
Instead of doing this, can we instead create the canonical type and create an incomplete translation? The idea of an incomplete type is deprecated.

2022-06-02 00:01 UTC, tasodorff requested changes
Minor changes requested.

2022-06-02 00:01 UTC, tasodorff commented on ontology/yaml/resources/HVAC/entity_types/DOAS.yaml
> +DOAS_FR_PAR_50A_1:
following up on this, we can delete this type and reuse the other one with MISSING fields in the translation.

2022-06-13 17:12 UTC, tasodorff commented
@ghairapetian please see comments and resolve merge conflicts.

2022-07-08 15:35 UTC, cstirdivant commented
@ghairapetian please fix validator errors

2022-07-19 19:08 UTC, cstirdivant commented on ontology/yaml/resources/HVAC/entity_types/AHU.yaml
> +AHU_CHWSC_EFVSC_FDPM3X_HTWHLSTC_HWSC_RCO2M_RSPC_SFM_SFVSC_SSPC_VOADM_VMADC:
@ghairapetian per this comment if this is actually a `DOAS` type, please move it to the DOAS.yaml file

2022-07-19 19:14 UTC, cstirdivant commented on ontology/yaml/resources/HVAC/entity_types/AHU.yaml
> +  - SFVSC
it may be redundant, but precendent states whenever `SFVSC` or `EFVSC` are implemented that the basic SS types be included, as well (`SFSS`, `EFSS`)

2022-07-26 21:37 UTC, tasodorff commented
@ghairapetian please make requested updates.

2022-09-07 10:07 UTC, closed without merging

2022-09-07 15:02 UTC, ghairapetian commented
I will make a new pull request with all the changes asked.