Update telemetry and entity type fields leak detection system
google/digitalbuildings pull request #587
Opened 2022-05-09 14:40 UTC by RathishKJ

2022-05-10 23:35 UTC, tasodorff requested changes

2022-05-10 23:35 UTC, tasodorff commented on ontology/yaml/resources/SAFETY/entity_types/LDS.yaml
> +  id: "a20f963a09c04c1cba76330dbec3e03c"
ID is not necessary; our system creates them.

2022-05-17 20:53 UTC, tasodorff approved these changes

2022-05-17 20:53 UTC, tasodorff commented on ontology/yaml/resources/fields/telemetry_fields.yaml
> +<<<<<<< Updated upstream
Please fix

2022-05-17 20:53 UTC, tasodorff commented on ontology/yaml/resources/fields/telemetry_fields.yaml
> +	- ON
Please fix

2022-05-17 20:53 UTC, tasodorff commented on ontology/yaml/resources/fields/telemetry_fields.yaml
> +	- OFF
please fix

2022-05-17 20:53 UTC, tasodorff commented on ontology/yaml/resources/fields/telemetry_fields.yaml
> +=======
please fix

2022-05-17 20:53 UTC, tasodorff commented on ontology/yaml/resources/fields/telemetry_fields.yaml
> +>>>>>>> Stashed changes
please fix

2022-05-17 20:54 UTC, tasodorff requested changes
fix remaining errors

2022-06-02 00:03 UTC, tasodorff commented
@RathishKJ please make requested changes.

2022-06-13 17:14 UTC, tasodorff requested changes
Please remove fields that aren't relevant to this PR.

2022-06-13 17:14 UTC, tasodorff commented on ontology/yaml/resources/fields/telemetry_fields.yaml
> +- defrost_run_status
since these aren't needed for this PR, please remove them. they are covered in another PR.

2022-06-24 15:29 UTC, RathishKJ commented
Closing the PR since it is already been defined in another pull request

2022-06-24 15:29 UTC, closed without merging