Update EM.yaml
google/digitalbuildings pull request #613
Opened 2022-06-04 10:00 UTC by RathishKJ

2022-06-13 18:31 UTC, tasodorff requested changes
Provide clarifications on one abstract type.

2022-06-13 18:31 UTC, tasodorff commented on ontology/yaml/resources/METERS/entity_types/ABSTRACT.yaml
> +  description: "Energy monitoring from Electrical Grid and Diesel Generator with run hours monitoring."
If these are coming from two separate, distinct sources then they should have distinct names. Which field serves which source? Please adjust field names. something like `generator_energy_accumulator` and `electrical_grid_energy_accumulator`.

2022-06-24 15:38 UTC, RathishKJ commented on ontology/yaml/resources/METERS/entity_types/ABSTRACT.yaml
> +  - run_time_accumulator_1
This is the runtime for the electricity from the grid and from the generators.

created separate fields 
  - generator_energy_accumulator
  - electricalgrid_energy_accumulator
  - generator_run_time_accumulator
  - electricalgrid_run_time_accumulator

2022-06-28 03:48 UTC, tasodorff approved these changes

2022-06-28 21:57 UTC, merged