Abstract apu
google/digitalbuildings pull request #620
Opened 2022-06-07 14:04 UTC by RathishKJ

2022-06-13 20:04 UTC, tasodorff requested changes
These all implement AHU, not APU (which isnt defined in the ontology or BDNS/BOS abbreviation standards doc).

2022-06-16 19:51 UTC, RathishKJ commented
> These all implement AHU, not APU (which isnt defined in the ontology or BDNS/BOS abbreviation standards doc). Also, these canonical types are all incomplete. They need to be fixed.

The canonicals have been completed with inclusion of new telemetry firlds and abstracts. This has been implemented under MAU.

2022-06-23 10:16 UTC, RathishKJ commented
> > These all implement AHU, not APU (which isnt defined in the ontology or BDNS/BOS abbreviation standards doc). Also, these canonical types are all incomplete. They need to be fixed.
> 
> The canonicals have been completed with inclusion of new telemetry fields and abstracts. This has been implemented under MAU.

The Airpurifier Unit is implemented under MAU with new abstract DFVSC3X catering to 3 fans coming in a single Air purifier unit. The air is discharged to the AHU rooms from the APU units

2022-06-29 17:24 UTC, tasodorff requested changes

2022-06-30 01:12 UTC, RathishKJ commented on ontology/yaml/resources/HVAC/entity_types/APU.yaml
> +APU_SS:
APU.yaml has been removed as an entity. All the associated canonicals comprising of APU has been deleted.

2022-06-30 05:04 UTC, RathishKJ commented on ontology/yaml/resources/HVAC/entity_types/ABSTRACT.yaml
> +MSM:
deleted the Abstract...

2022-06-30 05:04 UTC, RathishKJ commented on ontology/yaml/resources/HVAC/entity_types/ABSTRACT.yaml
> +MSM3X:
deleted the Abstract MSM3X...

2022-06-30 05:05 UTC, RathishKJ commented on ontology/yaml/resources/HVAC/entity_types/ABSTRACT.yaml
> +  - current_sensor_1
deleted the abstract...

2022-06-30 05:13 UTC, RathishKJ commented on ontology/yaml/resources/HVAC/entity_types/MAU.yaml
> +  - DFVSC3X
This has supply fan and therefore, the DFVSC3X changed to SFVSC3X and SFSS3X has been added to the canonical.

2022-06-30 17:11 UTC, RathishKJ commented on ontology/yaml/resources/HVAC/entity_types/ABSTRACT.yaml
> +FRDM3X:
Deleted the abstract...

2022-07-01 05:09 UTC, tasodorff approved these changes

2022-07-06 15:41 UTC, merged