Update telemetry_fields.yaml
google/digitalbuildings pull request #627
Opened 2022-06-08 06:44 UTC by Karthi8883

added telemetry field for UPS Bypass reversed status

2022-06-14 06:39 UTC, Karthi8883 commented
we have raised this  request to test the access to master.

2022-06-14 12:20 UTC, Karthi8883 commented on ontology/yaml/resources/ELECTRICAL/entity_types/ABSTRACT.yaml
> +  - bypass_phase_reversed
This binary point provides the status of bypass phase, whether it is normal or reversed. modified the subfield to status now. hope this is fine.

2022-06-14 23:46 UTC, mschulze17 commented
@tasodorff back to you

2022-06-17 00:03 UTC, tasodorff requested changes
see comments

2022-06-17 00:03 UTC, tasodorff commented on ontology/yaml/resources/HVAC/entity_types/ABSTRACT.yaml
> +  - zone_particle_concentration_sensor
air or water? you can use `particle_concentration_sensor` which already exists, or you can add one for `zone_air_particle_concentration_sensor`.

2022-06-22 03:42 UTC, Karthi8883 commented on ontology/yaml/resources/ELECTRICAL/entity_types/ABSTRACT.yaml
> +  - bypass_phase_status
Updated in opt_uses. Kindly verify.

2022-06-29 05:27 UTC, tasodorff commented
resolve conflicts so we can run validation. ensure validation passes for every PR before submitting. you can use local validator tools to do this.

2022-07-06 07:03 UTC, Karthi8883 commented
Updated as part of [https://github.com/google/digitalbuildings/pull/669/]

2022-07-06 07:03 UTC, closed without merging