Energy Meter Fields added
google/digitalbuildings pull request #645
Opened 2022-06-15 13:31 UTC by darshanjain12

2022-06-29 17:55 UTC, tasodorff requested changes

2022-06-29 17:55 UTC, tasodorff commented on ontology/yaml/resources/subfields/subfields.yaml
> +  reactiveenergy: "Measures alternating exchange of stored energy in inductors and capacitors"
remove

2022-06-29 17:55 UTC, tasodorff commented on ontology/yaml/resources/units/units.yaml
> +reactiveenergy:
remove

2022-06-30 12:16 UTC, darshanjain12 commented on ontology/yaml/resources/units/units.yaml
> +reactiveenergy:
Done

2022-07-12 23:57 UTC, cstirdivant approved these changes

2022-07-13 22:39 UTC, merged