Update ABSTRACT UPS.yaml
google/digitalbuildings pull request #665
Opened 2022-06-19 19:19 UTC by RathishKJ

2022-06-30 03:41 UTC, tasodorff requested changes

2022-06-30 03:41 UTC, tasodorff commented on ontology/yaml/resources/ELECTRICAL/entity_types/ABSTRACT.yaml
> +
revert if just whitespace.

2022-06-30 03:44 UTC, RathishKJ commented on ontology/yaml/resources/ELECTRICAL/entity_types/ABSTRACT.yaml
> +
White space has been removed...

2022-07-01 05:04 UTC, tasodorff approved these changes

2022-07-05 22:13 UTC, merged