Update_LDS.yaml
google/digitalbuildings pull request #694
Opened 2022-06-27 06:26 UTC by Karthi8883

Updated H2 gas monitoring points

2022-06-30 03:02 UTC, tasodorff commented
validator errors

2022-07-08 17:55 UTC, cstirdivant requested changes

2022-07-08 17:55 UTC, cstirdivant commented on ontology/yaml/resources/SAFETY/entity_types/LDS.yaml
> +LDS_H2M:
This seems to break precedent for the LDS types, all other types are implement `alarm` fields, is this truly a H2 sensor? or is it an alarm?

2022-07-26 21:29 UTC, tasodorff approved these changes

2022-07-26 21:31 UTC, mschulze17 commented
@cstirdivant yours to merge :)

2022-07-27 00:03 UTC, merged