RO WATER SYSTEM
google/digitalbuildings pull request #770
Opened 2022-09-20 15:59 UTC by darshanjain12

RO WATER SYSTEM with new  fields added for TDS

2022-10-24 20:30 UTC, tasodorff requested changes

2022-10-24 20:30 UTC, tasodorff commented on ontology/yaml/resources/units/units.yaml
> +- miligrams_per_litre
use american standard spelling: "liter"

2022-10-25 02:23 UTC, darshanjain12 commented on ontology/yaml/resources/units/units.yaml
> +- miligrams_per_litre
Done the required changes

2022-10-25 15:31 UTC, tasodorff approved these changes

2022-10-25 15:58 UTC, merged