Project import generated by Copybara.
google/digitalbuildings pull request #840
Opened 2022-11-16 17:04 UTC by cstirdivant

Project import generated by Copybara.

2022-11-16 17:37 UTC, charbull requested changes
it is better to leave the .png out
it will mess up links in the readme for Travis.

2022-11-21 17:50 UTC, trav3711 commented
Or you can rename the links in the abel readme. 

https://github.com/google/digitalbuildings/blob/ed2bcf45325fcb718aacccf3a4cbbb29e214d178/tools/abel/README.md?plain=1#L88

2022-11-21 18:53 UTC, cstirdivant commented
@charbull hacky, but i just moved the file to the original file path

@trav3711 no updates made to the readme, but thank you for your help :)

2022-11-21 19:19 UTC, charbull approved these changes

2022-11-21 19:21 UTC, merged