Upgrade digitalbuildings tools to depend on Python 3.11
google/digitalbuildings pull request #855
Opened 2022-12-12 19:38 UTC by trav3711

2022-12-16 21:01 UTC, trav3711 commented
I can find the bug that keeps breaking the scoring tool. It's not any of the parsing logic because the scoring tool depends on the instance validator's `Deserilaize` method for that which passes its own tests. My hunch is something in python's standard library has changed causing the scoring tool to break with the 3.11 migration. 

I was thinking the `map()` method changed but no dice yet. There's also not much documentation for python 3.11 bugs yet, but the release is considered stable.

https://www.geeksforgeeks.org/python-map-function/

2023-01-24 05:19 UTC, tasodorff commented
@trav3711 is this still valid or should we close?

2023-01-27 19:08 UTC, sypks commented
patched scoring tool and running github actions now

2023-01-27 19:44 UTC, sypks commented
patch success. please review @trav3711 @tasodorff @charbull

2023-01-27 19:58 UTC, trav3711 commented on tools/scoring/score/parse_config.py
> +          PROPOSED: aggregate_translations(proposed_entity),
Why did the f string literal break the scoring tool? Is that a change in 3.11?

2023-01-27 19:59 UTC, trav3711 commented
Looks like you need to get your CLA approved? Not sure how this is done but I thought you did this already?

2023-01-27 20:08 UTC, charbull requested changes
make the version stricter

2023-01-27 20:08 UTC, charbull commented on tools/abel/setup.py
> +    python_requires='>=3.11',
I propose to keep it = for now so we dont encounter future changes/surprises, wdyt?

2023-01-27 20:52 UTC, closed without merging