Added alarms to telemetry fields and abstracts
google/digitalbuildings pull request #898
Opened 2023-01-26 17:35 UTC by EugeniaDickson

2023-01-26 20:01 UTC, cstirdivant requested changes

2023-01-26 20:01 UTC, cstirdivant commented on ontology/yaml/resources/HVAC/entity_types/ABSTRACT.yaml
> +  - failed_discharge_air_temperature_alarm
needs to be enumerated

2023-01-26 20:01 UTC, cstirdivant commented on ontology/yaml/resources/HVAC/entity_types/ABSTRACT.yaml
> +  - failed_zone_air_temperature_alarm
enumeration

2023-01-26 20:01 UTC, cstirdivant commented on ontology/yaml/resources/HVAC/entity_types/ABSTRACT.yaml
> +  - failed_zone_air_temperature_alarm
enumeration

2023-01-30 17:00 UTC, cstirdivant requested changes
please check single quotes around the id strings - I believe they need to be double quotes

2023-01-30 17:00 UTC, cstirdivant commented on ontology/yaml/resources/subfields/subfields.yaml
> +  cafe: "Applies for cafe areas within building"
Need a better description here

2023-01-30 17:00 UTC, cstirdivant commented on ontology/yaml/resources/subfields/subfields.yaml
> +  kitchen: "Applies for kitchen areas within building"
Please make a better description.

2023-01-30 17:08 UTC, tasodorff commented on ontology/yaml/resources/subfields/subfields.yaml
> +  cafe: "Applies for cafe areas within building"
iirc we decided to remove cafe and kitchen as descriptors.

2023-01-30 18:21 UTC, cstirdivant approved these changes

2023-01-30 18:22 UTC, cstirdivant approved these changes

2023-01-30 18:23 UTC, merged